# Generated by Django 4.2.5 on 2023-09-23 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.cadet')),
            ],
        ),
    ]
